version: "3"
services:
  ecommerce-service:
    build: ${ECOMMERCE_SERVICE_PATH}/Docker/app/.
    container_name: ${ECOMMERCE_SERVICE_NAME}
    command: ["npm", "run", "dev"]
    env_file:
      - ${ECOMMERCE_SERVICE_PATH}/Docker/app/.env
      - .env
    environment:
      - SEQUELIZE_HOST=ecommerce-mysql
      - SEQUELIZE_DATABASE=${ECOMMERCE_MYSQL_DATABASE}
      - SEQUELIZE_PORT=3306
    ports:
      - "${ECOMMERCE_APP_PORT}:8080"
    depends_on:
      - ecommerce-mysql
    networks:
      - ecommerce-net
    volumes:
      - ${ECOMMERCE_SERVICE_PATH}/src:/app/src
      - ${ECOMMERCE_SERVICE_PATH}/tests:/app/tests

  ecommerce-mysql:
    image: mysql:8.0
    container_name: ${ECOMMERCE_MYSQL_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${ECOMMERCE_MYSQL_DATABASE}
    ports:
      - "${ECOMMERCE_MYSQL_PORT}:3306"
    volumes:
      - ./ecommerce-service/Docker/database:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
